name: CI

on:
  push: { branches: ["0.x"] }
  pull_request: { branches: ["0.x"] }

jobs:
  commits:
    name: Commitlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1000

      - name: Lint commits
        uses: docker://registry.k1.zportal.co.uk/practically-oss/conventional-tools:0.x
        with:
          args: conventional-tools commitlint -l1

  luacheck:
    name: Luacheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install luarocks
        run: sudo apt update && sudo apt install -y luarocks

      - name: Install luacheck
        run: sudo luarocks install luacheck

      - name: Run luacheck
        run: luacheck .

  clang-format:
    name: Clang Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y clang-format findutils

      - name: Run clang format
        run: find ./cpp -name "*.cpp" -o -name "*.hpp" | xargs clang-format -Werror --dry-run

  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y luajit build-essential pkg-config cmake

      - name: Build
        run: cmake -DCMAKE_BUILD_TYPE=Release -B build/Release && (cd build/Release; make -j)

      - name: Test
        run: find lua -name "*_test.lua" | xargs luajit scripts/test.lua
